# Generated by Django 4.1.5 on 2023-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graf20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('indods', models.CharField(max_length=50)),
                ('indicadorinterno', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('estudio', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=100)),
                ('perfil', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'graf20',
            },
        ),
    ]
